name: PGP Key Maintenance

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: read-all

env:
  KEY_NAME: vlsi/test-pgp-key
  KEY_EMAIL: vlsi--test-pgp-keys@example.org
  KEY_LIFETIME: 1825
jobs:
  pgp-key-maintenance:
    name: PGP key maintenance
    secrets: inherit
    uses: vlsi/provision-release-pgp-key/.github/workflows/pgp-key-maintenance.yaml@main
    with:
      key-name: vlsi/test-pgp-key
      key-email: vlsi--test-pgp-keys@example.org
      key-lifetime: 1825
